baseURL = "https://vincentlannurien.com/"
languageCode = "en-us"
title = "Vincent Lannurien"
theme = "maverick"

[params]
  logo = '/assets/favicon.ico'
  description = "Some notes that made their way out here"
  author = 'Vincent Lannurien'

[permalinks]
  pages = "/:slug"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "essential"
    name = "📝 Essential"
    url = "/essential/"
    weight = "1"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'nord'
    tabWidth = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]