name = "Vincent"
license = "MIT"
licenselink = "https://opensource.org/license/mit"
description = "Essential theme"

# The home page of the theme, where the source can be found.
homepage = "https://vincentlannurien.com"

# If you have a running demo of the theme.
demosite = "https://vincentlannurien.com"

tags = ["blog"]
features = ["ultra fast", "responsive"]

# If the theme has a single author
[author]
    name = "Lannurien, Vincent"
    homepage = "https://vincentlannurien.com"
